// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFWkKc7BTPsuOwU_hq9cndTDYWUstVcFs',
    appId: '1:48965669266:web:6c2531278f1ae25103b14b',
    messagingSenderId: '48965669266',
    projectId: 'oxyshine-cd6a7',
    authDomain: 'oxyshine-cd6a7.firebaseapp.com',
    storageBucket: 'oxyshine-cd6a7.appspot.com',
    measurementId: 'G-QQLSGTG4WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGzfjmU64TRTYYJP8sA6U94jV7GwDjLRc',
    appId: '1:48965669266:android:74478223665e986103b14b',
    messagingSenderId: '48965669266',
    projectId: 'oxyshine-cd6a7',
    storageBucket: 'oxyshine-cd6a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCx0lZyq2vtDl6HSPXeYwRZkCDwgt-6sM',
    appId: '1:48965669266:ios:c76be0578eec852503b14b',
    messagingSenderId: '48965669266',
    projectId: 'oxyshine-cd6a7',
    storageBucket: 'oxyshine-cd6a7.appspot.com',
    androidClientId: '48965669266-knq03ista8ok1cnpo2hfrot9slo5gk5t.apps.googleusercontent.com',
    iosClientId: '48965669266-d8j6okfkumiej6p9ifup57bp48pnh60u.apps.googleusercontent.com',
    iosBundleId: 'com.example.oxyshine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCx0lZyq2vtDl6HSPXeYwRZkCDwgt-6sM',
    appId: '1:48965669266:ios:c76be0578eec852503b14b',
    messagingSenderId: '48965669266',
    projectId: 'oxyshine-cd6a7',
    storageBucket: 'oxyshine-cd6a7.appspot.com',
    androidClientId: '48965669266-rs2ld7jgcoun910lpi7iqsgnncqtds67.apps.googleusercontent.com',
    iosClientId: '48965669266-d8j6okfkumiej6p9ifup57bp48pnh60u.apps.googleusercontent.com',
    iosBundleId: 'com.oxyshine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFWkKc7BTPsuOwU_hq9cndTDYWUstVcFs',
    appId: '1:48965669266:web:e67ad657fb4aee4b03b14b',
    messagingSenderId: '48965669266',
    projectId: 'oxyshine-cd6a7',
    authDomain: 'oxyshine-cd6a7.firebaseapp.com',
    storageBucket: 'oxyshine-cd6a7.appspot.com',
    measurementId: 'G-CM2V218JYG',
  );

}